### ISSUE TITLE
Failing to launch some Services on Docker-compose

### ISSUE THREAD

**Issue by torrybr** [sergio11/document_search_engine_architecture#1]
Hi Sergio11,

Awesome project you have and thanks for documenting it all out so well! 👏

1) Nifi service is failing to start when running the docker compose file.
```
2021-08-31 21:20:54,733 INFO [main] org.apache.nifi.NiFi Launching NiFi...

2021-08-31 21:21:04,127 INFO [main] o.a.n.p.AbstractBootstrapPropertiesLoader Determined default application properties path to be '/opt/nifi/nifi-current/./conf/nifi.properties'

2021-08-31 21:21:04,653 INFO [main] o.a.nifi.properties.NiFiPropertiesLoader Loaded 202 properties from /opt/nifi/nifi-current/./conf/nifi.properties

2021-08-31 21:21:05,449 ERROR [main] o.a.nifi.properties.NiFiPropertiesLoader Clustered Configuration Found: Shared Sensitive Properties Key [nifi.sensitive.props.key] required for cluster nodes

2021-08-31 21:21:05,479 ERROR [main] org.apache.nifi.NiFi Failure to launch NiFi due to java.lang.IllegalArgumentException: There was an issue decrypting protected properties

java.lang.IllegalArgumentException: There was an issue decrypting protected properties

at org.apache.nifi.NiFi.initializeProperties(NiFi.java:346)

at org.apache.nifi.NiFi.convertArgumentsToValidatedNiFiProperties(NiFi.java:314)

at org.apache.nifi.NiFi.convertArgumentsToValidatedNiFiProperties(NiFi.java:310)

at org.apache.nifi.NiFi.main(NiFi.java:302)

Caused by: org.apache.nifi.properties.SensitivePropertyProtectionException: Sensitive Properties Key [nifi.sensitive.props.key] not found: See Admin Guide section [Updating the Sensitive Properties Key]

at org.apache.nifi.properties.NiFiPropertiesLoader.getDefaultProperties(NiFiPropertiesLoader.java:220)

at org.apache.nifi.properties.NiFiPropertiesLoader.get(NiFiPropertiesLoader.java:209)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at org.apache.nifi.NiFi.initializeProperties(NiFi.java:341)

... 3 common frames omitted
```

2) activiti/rabbitmq-stomp is archived and cannot be pulled when running the docker-compose. Is it okay to replace with an alternative like `jorgeacetozi/rabbitmq-stomp`?

Thanks!

**Comment by sergio11** [comment]
Hello, Thank you for your feedback and for notifying me of the errors. It seems that it is a problem of the new version of Nifi available in Docker Hub, I will have to investigate further, the project was developed using version 1.12.0, so for the container to work correctly you should explicitly indicate the version instead of the latest like this:

```
FROM  apache/nifi:1.12.0
COPY ./conf/core-site.xml /opt/nifi/conf/
COPY ./conf/hdfs-site.xml /opt/nifi/conf/
COPY ./templates/Ingest_Files_Pipeline_Template_v9.xml /opt/nifi/nifi-current/conf/templates
COPY --chown=nifi:nifi flow.xml.gz /opt/nifi/nifi-current/conf/
EXPOSE 8080
```
Anyway I will upload the update as soon as I can, on the other hand, I have not tested that image that you comment, it may be compatible, it will surely try to mount the container with the image locally using the Dockerfile of the [repository](https://github.com/AlfrescoArchive/rabbitmq-stomp) even if the image is no longer in DockerHub.

Hope that helps, best regards. :)

**Comment by sergio11** [comment]
The Hash thing seems like a fantastic improvement to me, it is clear that using the name is not robust and adequate enough. Feel free to make whatever contributions you deem appropriate.
 A greeting
